### ISSUE TITLE
why don't wrap AWS SDK instead?

### ISSUE THREAD

**Issue by drAlberT** [Interfacelab/ilab-aws-media-cloud-sdk#1]
wouldn't be better to require the official SDK in composer and then add your customization around it?

**Comment by jawngee** [comment]
Because a lot of WordPress plugins use old and older versions of the SDK.  It was an issue so I re-namespaced the AWS SDK (my only customization).  As far as I know, you can't re-namespace an entire SDK with just composer.

**Comment by jawngee** [comment]
Using composer with WordPress is a bit of a shit show, tbh.

**Comment by drAlberT** [comment]
You could just include your preferred SDK version directly in your project then .. for example using git submodules ..

The current implementation makes quite hard to clearly see and understand what your "customizations" are over the original SDK ... it is a matter of security too IMHO ..

**Comment by drAlberT** [comment]
composition over inheritance .. over fork and override ;)

**Comment by jawngee** [comment]
Submodules are irrelevant when you package the plugin up for the wordpress plugin repository.  You'll have class collisions unless you re-namespace.

What does composition over inheritance have to do with changing the name of a namespace?

**Comment by drAlberT** [comment]
I mean include the SDK src in your own codebase via submodules (or whatever tool you prefer) .. then wrap it instead of modifying it.  other WP code will not be affected by *your private copy* of your private clone of your preferred release of the original SDK .. 

About "over .. over .. " it was a words-joke .. never mind

**Comment by jawngee** [comment]
You are missing the point.

You can't wrap a namespace.  If I write wrapper classes around the AWS SDK, the fact that there are mismatched AWS SDKs being loaded via autoloading (composer or not) is still a problem.

Not to mention the effort involved.  To renamespace this SDK I just run a script that is `sed` commands.

**Comment by jawngee** [comment]
And you can't use the AWS SDK without autoloading, so *shrug*

**Comment by drAlberT** [comment]
The main point was "please find a way to make **evident** what you touched in the AWS SDK" .. 

As a end-user I'd like to be sure you (you as a generic developer of a lib for my project not you as the particular person) don't introduced regressions, bug or other not wanted stuff in the official package .. 

Don't blame us (users) but you can understand that the reputation of AWS if quite a bit higher and we trust AWS a little bit more than you (which we trust in fact otherwise we were not here writing) ...

So, how can we see (not digging in cross repo diffs) what is your add value and what is the main AWS original code?

**Comment by jawngee** [comment]
This repo is for a specific set of WordPress plugins that we produce.  I don't understand why anyone but people in our org would even be looking at it or want to use it.

Stick with the regular AWS SDK, this lib *isn't for your project*.  It's for a well respected WordPress plugin (https://wordpress.org/plugins/ilab-media-tools/) that's been in use for the last 3+ years and used on fortune 100 company websites (our clients).

So, therefore, the onus is on you to diff it with Amazon's SDK, it's not on me to prove anything.

I also don't really think you know what you are talking about because you are definitely demonstrating you don't have a grasp of the issues that required us to create this repo in the first place.

So stick with the AWS SDK.

**Comment by drAlberT** [comment]
I reached this repo as user of your WP media tool .. so I'm not choosing to use it, it is required by your plugin ..

anyway, I'll not insist. Have a great day
